# PyTorch Useful Methods

In [1]:
import torch

### expand: copy the given tensor and concat those at desired dimension.

In [27]:
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
print(x.size())

torch.Size([2, 1, 2])


In [28]:
x

tensor([[[1., 2.]],

        [[3., 4.]]])

In [34]:
y = x.expand(*[2, 4, 2])

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 4, 2])


#### Implement expand with cat.

In [6]:
y = torch.cat([x, x, x], dim=1)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### randperm: Random Permutation

In [7]:
x = torch.randperm(10)

print(x)
print(x.size())

tensor([6, 4, 8, 0, 2, 9, 1, 7, 3, 5])
torch.Size([10])


### argmax: Return index of maximum values

In [9]:
x = torch.randperm(3**3).reshape(3, 3, -1)

print(x)
print(x.size())

tensor([[[16, 20, 26],
         [ 3, 25,  4],
         [ 2, 11,  9]],

        [[15, 12, 13],
         [ 8, 10, 23],
         [17,  0, 19]],

        [[21, 24, 18],
         [ 6,  5, 22],
         [14,  1,  7]]])
torch.Size([3, 3, 3])


In [10]:
x

tensor([[[16, 20, 26],
         [ 3, 25,  4],
         [ 2, 11,  9]],

        [[15, 12, 13],
         [ 8, 10, 23],
         [17,  0, 19]],

        [[21, 24, 18],
         [ 6,  5, 22],
         [14,  1,  7]]])

In [11]:
y = x.argmax(dim=-1)

print(y)
print(y.size())

tensor([[2, 1, 1],
        [0, 2, 2],
        [1, 2, 0]])
torch.Size([3, 3])


### topk: Return tuple of top-k values and indices.

In [18]:
values, indices = torch.topk(x, k=1, dim=2)

print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


In [19]:
values

tensor([[[26],
         [25],
         [11]],

        [[15],
         [23],
         [19]],

        [[24],
         [22],
         [14]]])

Note that topk didn't reduce the dimension, even in $k=1$ case.

In [9]:
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[25, 16, 24],
        [17, 22, 12],
        [23, 21, 26]])
tensor([[2, 1, 0],
        [2, 1, 2],
        [2, 1, 0]])


In [10]:
print(x.argmax(dim=-1) == indices.squeeze(-1))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [11]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

print(x.argmax(dim=-1) == indices[:, :, 0])

torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Sort by using topk

In [20]:
target_dim = -1
values, indices = torch.topk(x,
                             k=x.size(target_dim),
                             largest=True)

print(values)

tensor([[[26, 20, 16],
         [25,  4,  3],
         [11,  9,  2]],

        [[15, 13, 12],
         [23, 10,  8],
         [19, 17,  0]],

        [[24, 21, 18],
         [22,  6,  5],
         [14,  7,  1]]])


### Topk by using sort

In [21]:
k=1
values, indices = torch.sort(x, dim=-1, descending=True)
values, indices = values[:, :, :k], indices[:, :, :k]

print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[26, 25, 11],
        [15, 23, 19],
        [24, 22, 14]])
tensor([[2, 1, 1],
        [0, 2, 2],
        [1, 2, 0]])


### masked_fill: fill the value if element of mask is True.

In [24]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [25]:
x

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [23]:
mask = x > 4

print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [16]:
y = x.masked_fill(mask, value=-1)

print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


### Ones and Zeros

In [17]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [18]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [19]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
